//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica_VI_IV_Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pelicula
    {
        public int PeliculasID { get; set; }
        public string Titulo { get; set; }
        public string Director { get; set; }
        public string AutorPrincipal { get; set; }
        public int No_Autores { get; set; }
        public double Duracion { get; set; }
        public int Estreno { get; set; }
    }
}
